# Generated by Django 2.2.13 on 2020-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginlogout', '0004_auto_20181103_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='phone',
        ),
    ]
