# Generated by Django 2.2.13 on 2020-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginlogout', '0005_auto_20200919_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=222, max_length=50),
            preserve_default=False,
        ),
    ]
